### ISSUE TITLE
OnPermissionRequested removed in 4.9.0.0?

### ISSUE THREAD

**Issue by leonardosnt** [RocketMod/Rocket.Unturned#18]
What happened with UnturnedPermissions.OnPermissionRequested, was moved? where?

**Comment by fr34kyn01535** [comment]
I removed it because i saw no reason to have it, why would you need it?

**Comment by leonardosnt** [comment]
To use in "no permission" message, but ok.

**Comment by fr34kyn01535** [comment]
This was initially used to offer additional permissions provider but was replaced by the interface.

**Comment by leonardosnt** [comment]
Ok, thanks.
