### ISSUE TITLE
PlayerUpdateHealth error

### ISSUE THREAD

**Issue by Viscerals** [RocketMod/Rocket.Unturned#25]
http://i.imgur.com/u7Pga9S.png
Been having this error after latest update.
I know you haven't fully updated it for the latest patch, just wanted to help by letting you know this was also a issue.
Thanks for the awesome plugin

**Comment by fr34kyn01535** [comment]
This is caused by an outdated plugin probably.

**Comment by Viscerals** [comment]
Alright thanks for the info!
