### ISSUE TITLE
Extreme CPU usage on Debian 8

### ISSUE THREAD

**Issue by izShelby** [RocketMod/Rocket.Unturned#26]
I am trying to run a Rocket Unturned server and after startup the server idles at 100-140% CPU usage (so around one and a half of eight available cores under full load). Whenever a player joins they experience rubber banding zombies, not being able to go near trees (???) and hits on zombies and players not doing any damage.

Since there is no error message I am really out of my depth here. I noticed that Rocket does some pretty extreme threading:
http://i.imgur.com/19PKYRD.png

It's a clean server, I removed all addons and am running Pei.

**Comment by fr34kyn01535** [comment]
Have you compared it to vanilla?

**Comment by izShelby** [comment]
I am an idiot. Should have tested that first. Sorry for bothering you mate.

**Comment by cellinho** [comment]
did you fixed it ?

same issue here.

https://gyazo.com/49e4f37c0ebc826b0972c6b874af6d2b
sometimes it goes over 2000%
