### ISSUE TITLE
Modded server bug

### ISSUE THREAD

**Issue by errorcode404wtf** [RocketMod/Rocket.Unturned#35]
OS: Ubuntu 15.04
Unturned: 3.16.2.0
Rocket: Linux 674

Description:
I'm not entirely sure if this is a bug. But I have a good feeling. When I launch my normal Unturned server it works fine, starts up, loads the world. Do this with Rocket installed, same thing. But when I get to installing mods is the interesting part. It will load all the way up to the first loading of the mods then completely stops. I've tried installing a whole new Unturned directory, I've tried subscribing to the mods on my account. Nothing seems to work, I also have a feeling this is due to it being 32 bit. If you're curious what it looks like here is a picture of the server crashed: http://imgur.com/a/Oa8tk

**Comment by fr34kyn01535** [comment]
Could you please share the logs?

**Comment by errorcode404wtf** [comment]
Seems to be fixed now in later updates. Or it could have been an error on my end. Idk, either way it works.
