### ISSUE TITLE
Extreme ping

### ISSUE THREAD

**Issue by errorcode404wtf** [RocketMod/Rocket.Unturned#36]
OS: Ubuntu 15.04
Unturned: 3.16.2.1
Rocket: 676 Linux

Description:
Well, we all know Unturned is a potato when it comes to optimization. But it can't be so bad when I'm getting thousands of ping on a dedicated server with 100MB/s upload and download... I'm not entirely sure where the problems lies, but this is very difficult to play with thousands of ping. Yes, I have pinged the server without Unturned. I'm getting about 40, and yes I have ran speed tests. The speeds are 100MB/s up and down. The ping normally get extremely high when there's a full server, so about 20 players. But most times I will still jump up to 300 ping with me only running Unturned on my Internet. I'm not sure if this is an Unturned bug or if this is Rocket but, this is where I'm going to have to shut it down until it's fixed... So, if you would look into it, either that or tell me if I should post a bug report on the Unturned page instead of here.

**Comment by cartman-2000** [comment]
It's not an issue with networking, the server needs "a lot" of raw single threaded performance to get a good TPS with a lot of players on the server. Most server cpu's that have a lot of threads but have a relatively low clock rate, won't really run Unturned server's that well.

**Comment by errorcode404wtf** [comment]
Can you read the title? We weren't lagging server wise. The ping was higher than the sky because (we believe) there was about 500 cars on the map. After I removed the vehicles file, it went back down to 80-100 ping. And btw, my dedicated has very good CPU.

**Comment by cartman-2000** [comment]
Yes, the cars are "very" hard on server cpu, especially if they have a lot of elements on them. The cars in Unturned are the worst thing in Unturned for server side processing power usage, far worse than the zombies, and at least 200-400 times worse than a single static element on the server(one's not attached to a vehicle.). To get a good TPS on a server it would be best to have less than 80-90 vehicles and less than around 400-500 elements on all of them combined(or less than 60-70 vehicles if you have more than ~20-30k elements on the server.).

This doesn't really have anything to do with rocket as it doesn't modify the way the vehicles function on the server, this is more of a performance issue with vehicles in Unturned. It may be a good idea to post it over at the Unturned's git issues.
https://github.com/SmartlyDressedGames/Unturned/issues
