### ISSUE TITLE
server will not start on linux

### ISSUE THREAD

**Issue by urlordjames** [RocketMod/Rocket.Unturned#75]
## issue
`./start.sh server1` will fail with message https://gist.github.com/urlordjames/544aefcaae38e7bea3a2e211c7af0399 server crashes before accepting input

## steps I used
I followed the tutorial on http://unturned.wikia.com/wiki/Hosting_a_Dedicated_Server then realized commands would not work so I figured I installed it incorrectly (which I probably did) and started from scratch following this tutorial https://youtu.be/z7aB-29esok.  I noticed the error so I tried this workaround https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/172 and realized it didn't change anything.  I ran update.sh then `./start.sh` and got a slightly different error https://gist.github.com/urlordjames/e81633ef4f7cd56c29b833fbf4a7872f.  I ran `./start.sh server1` figuring I forgot to add server1 at the end and got yet another error https://gist.github.com/urlordjames/4a3240ee12978a58c355d984326acdaa (similar to first error).

## os
Ubuntu 18.04.1 LTS

**Comment by urlordjames** [comment]
well, time to install linux on another one of my many craptops.

**Comment by fr34kyn01535** [comment]
Well, you could use any linux / Ubuntu distro, we only have recipes for Ubuntu 14 and 16, you'd need to figure out what is missing on your own. Feel free to contribute a recipe if you succeeded.

**Comment by RechtVH** [comment]
Sorry for getting involved here.

I have installed literally 100's of ubuntu servers with unturned, and , yes i seem to forget this everytime, this is still an issue today and if not done even if you gave followed all the guides to the letter, your server wont start. 

After all steps are done with installation, before you run the server by ./start "instance" you must ensure the following:

cd /steamcmd then
cp steamcmd/linux32/steamclient.so /lib
cp steamcmd/linux64/steamclient.so /lib64

Hope this helps.

**Comment by urlordjames** [comment]
Just to clarify, you're supposed to create a new directory called lib64?

**Comment by fr34kyn01535** [comment]
What @RechtVH is adding here is no hidden knowledge. All of this is mentioned at https://github.com/RocketMod/Rocket.Unturned/tree/legacy/Rocket.Unturned/Scripts/Linux and in the scripts in that folder.
