### ISSUE TITLE
 I need help to create Unturned server to VPS

### ISSUE THREAD

**Issue by DiKi777** [RocketMod/Rocket.Unturned#8]
Hello friends. I need help to create Unturned server to VPS. I have 10 days I can not move. Can someone explain in detail. https://github.com/RocketMod/Rocket.Unturned/tree/f76d889fd4bfe865d443104f4f161c1821d8eb44/Scripts/Linux It does not help, it prints an error. Reinstall OS Linux Debian 86_64. Can install any kind will tell new

**Comment by DiKi777** [comment]
Can you help me?

2015-12-21 16:18 GMT+06:00 fr34kyn01535 <notifications@github.com>:

**Comment by DiKi777** [comment]
xf86OpenConsole: Cannot find a free VT: Invalid argument VDS 
i dont know. What is it?

**Comment by fr34kyn01535** [comment]
I guess the x server is not running, but we don't do linux os support. Figure it & learn to google issues..
