### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by Fingrebrigt** [RocketMod/Rocket.Unturned#80]
MissingMethodException: Method not found: 'SDG.Unturned.ItemAsset.get_isPro'. - ZaupFeast.Feast.OnLevelWasLoaded ()
Dwnloaded the newest ZaupFeast build "196" and i keep getting this error line in console whenever i launch the server.

**Comment by Trojaner** [comment]
This is an issue with ZaupFeast plugin and is not related to RocketMod.
The plugin is heavily outdated.

**Comment by cartman-2000** [comment]
The plugin would need to be recompiled against the newer builds of unturned for it to work.
