### ISSUE TITLE
Server not running properly -- "This server lost your connection"

### ISSUE THREAD

**Issue by piyachetk** [RocketMod/Rocket.Unturned#81]
I am running the server on Ubuntu 18.04. I've already installed all of the prerequisites. The client is able to connect to the server via port 27016, to acquire some browser data, but the server is not responding from port 27015, the main port which the game is supposed to be running on. I've tracked the connection from the client using packet sniffers and some other networking tools, and I can confirm that the server really is doing nothing on port 27015. Localhost is also not responding from port 27015, which means that something is wrong with the Unturned server itself. Here is my Commands.dat file:

> map Russia
port 27015
maxplayers 8
Timeout 10000
Cheats

The console shows no error and the server seems to be able to load maps and assets just fine. There was an exception regarding some XML stuff which I've ignored but I don't think it is the cause of the problem. I am wondering if anyone is also having this problem.

**Comment by Trojaner** [comment]
Report to Unturned, this is not a RocketMod issue.
