### ISSUE TITLE
Zero-size xml configs after disk quota exceeded

### ISSUE THREAD

**Issue by D-AIRY** [RocketMod/Rocket.Unturned#82]
If server exceeded disk quota for some reason, most likely some of configs will break, and server won't launch again. Old configs shouldn't be deleted in case of new one's write is failed. Consider to use temp files to write and rename it after success.

**Comment by Trojaner** [comment]
To be honest this is a very special case, there are no plans to support this scenario.
However, RM5 may have magically fixed this as well.
