### ISSUE TITLE
3.29.5 Default Perms Config Error

### ISSUE THREAD

**Issue by RainOfPain125** [RocketMod/Rocket.Unturned#88]
3/7 of my servers are experiencing this error. The config I used before on these 3 servers were just fine, but as of this update they are not. I deleted them and used the default ones, which those produced the same error.

https://pastebin.com/uqRVS3RV

**Comment by RainOfPain125** [comment]
Small edit: The default files did not auto-generate. I did /save /shutdown and no new perms.xml file was created, not expected.

**Comment by Trojaner** [comment]
Support for RM4 has been dropped.
