### ISSUE TITLE
Scope glass being shown while in vanish

### ISSUE THREAD

**Issue by megoesrawr** [RocketMod/Rocket.Unturned#94]
There is a weird issues with scopes that will show the glass bit, white and in the corner. this happens if the gun is on your back or equipped.
Proof:
![57894849-88b9c380-7816-11e9-814d-06aee3657510](https://user-images.githubusercontent.com/7830406/60463727-bf0e9f00-9c1a-11e9-9dbc-0620b904e0f1.jpg)

(That is the 10x scope from Ireland but, it also happens with modded scopes)
Rocketmod 4 is what I'm using.

**Comment by Charterino** [comment]
This is unturned issue.

**Comment by megoesrawr** [comment]
https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues/791#issuecomment-503638400
