### ISSUE TITLE
Linux wget command Permanent Redirect

### ISSUE THREAD

**Issue by KyeNormanGill** [RocketMod/Rocket.Unturned#95]
In the scripts here https://github.com/RocketMod/Rocket.Unturned/tree/legacy/Rocket.Unturned/Scripts/Linux

One of the steps is to use wget
```wget ci.rocketmod.net/job/Rocket.Unturned%20Linux/lastSuccessfulBuild/artifact/Rocket.Unturned/bin/Release/Rocket.zip -O rocket.zip```

It errors with status code 308 saying Permanent Redirect.

After watching the how-to install on ubuntu video, I realised the link had `https://` before the link. Running that fixed it.

This read me needs to be updated.

**Comment by Trojaner** [comment]
Regardless of the fix, the download link is wrong. Also legacy is not supported anymore.
